[build]
  publish = "dist"
  command = "npm run build"

# Pre-rendering configuration
[prerender]
  config = "prerender-config.json"

# Configurazione proxy per reindirizzare le chiamate API
[[redirects]]
  from = "/api/*"
  to = "https://gestionaleaffitti.onrender.com/api/:splat"
  status = 200
  force = true

# Reindirizzamenti per le lingue senza slash alla fine
# Questi devono essere prima degli altri reindirizzamenti per avere precedenza
[[redirects]]
  from = "/en"
  to = "/en/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/fr"
  to = "/fr/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/de"
  to = "/de/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/es"
  to = "/es/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/en-gb"
  to = "/en-gb/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/it"
  to = "/it/index.html"
  status = 200
  force = true

# Configurazione per le pagine multilingua con percorsi più specifici
[[redirects]]
  from = "/it/*"
  to = "/it/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/fr/*"
  to = "/fr/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/de/*"
  to = "/de/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/es/*"
  to = "/es/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/en-gb/*"
  to = "/en-gb/index.html"
  status = 200
  force = true

# Reindirizzamento di fallback per SPA (solo per percorsi non linguistici)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Questa configurazione aiuta Netlify a rilevare crawler e bot per servire versioni prerendered
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"

# Configurazione MIME type per assets
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

# Questa opzione attiva il rilevamento automatico di bot per prerendering
[context.production]
  environment = { NETLIFY_EXPERIMENTAL_DETECT_BOTS_AND_DISABLE_CACHE = "true" }

# Configurazione header per sicurezza e ottimizzazione
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google-analytics.com https://www.googletagmanager.com https://region1.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' data: https://fonts.googleapis.com https://fonts.gstatic.com; connect-src 'self' https://api.tenoris360.com https://gestionaleaffitti.onrender.com https://www.google-analytics.com https://region1.google-analytics.com;" 