[build]
  publish = "dist"
  command = "npm run build"

# Configurazione proxy per reindirizzare le chiamate API
[[redirects]]
  from = "/api/*"
  to = "https://gestionaleaffitti.onrender.com/api/:splat"
  status = 200
  force = true

# Header per le SPA (Single Page Applications)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

# Questa configurazione aiuta Netlify a rilevare crawler e bot per servire versioni prerendered
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"

# Questa opzione attiva il rilevamento automatico di bot per prerendering
[context.production]
  environment = { NETLIFY_EXPERIMENTAL_DETECT_BOTS_AND_DISABLE_CACHE = "true" } 